=== team-lasalca/diversity-algo/phystech-master/example/output_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "courier_id",
      "action",
      "order_id",
      "point_id"
    ],
    "properties": {
      "courier_id": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10000
      },
      "action": {
        "type": "string",
        "enum": [
          "pickup",
          "dropoff"
        ]
      },
      "order_id": {
        "type": "integer",
        "minimum": 10001,
        "maximum": 30000
      },
      "point_id": {
        "type": "integer",
        "minimum": 30001,
        "maximum": 80000
      }
    }
  }
}

=== team-lasalca/diversity-algo/phystech-master/kamil/cls_output.json
[{"courier_id": 9, "action": "pickup", "order_id": 17067, "point_id": 47067}, {"courier_id": 9, "action": "pickup", "order_id": 13798, "point_id": 43798}, {"courier_id": 9, "action": "pickup", "order_id": 14256, "point_id": 44256}, {"courier_id": 9, "action": "pickup", "order_id": 14201, "point_id": 44201}, {"courier_id": 9, "action": "dropoff", "order_id": 13798, "point_id": 63798}, {"courier_id": 9, "action": "dropoff", "order_id": 14201, "point_id": 64201}, {"courier_id": 9, "action": "dropoff", "order_id": 14256, "point_id": 64256}, {"courier_id": 9, "action": "dropoff", "order_id": 17067, "point_id": 67067}, {"courier_id": 11, "action": "pickup", "order_id": 10260, "point_id": 40260}, {"courier_id": 11, "action": "pickup", "order_id": 15290, "point_id": 45290}, {"courier_id": 11, "action": "dropoff", "order_id": 10260, "point_id": 60260}, {"courier_id": 11, "action": "dropoff", "order_id": 15290, "point_id": 65290}, {"courier_id": 13, "action": "pickup", "order_id": 13574, "point_id": 43574}, {"courier_id": 13, "action": "pickup", "order_id": 12679, "point_id": 42679}, {"courier_id": 13, "action": "pickup", "order_id": 16859, "point_id": 46859}, {"courier_id": 13, "action": "dropoff", "order_id": 12679, "point_id": 62679}, {"courier_id": 13, "action": "dropoff", "order_id": 13574, "point_id": 63574}, {"courier_id": 13, "action": "dropoff", "order_id": 16859, "point_id": 66859}, {"courier_id": 17, "action": "pickup", "order_id": 14517, "point_id": 44517}, {"courier_id": 17, "action": "pickup", "order_id": 16319, "point_id": 46319}, {"courier_id": 17, "action": "dropoff", "order_id": 14517, "point_id": 64517}, {"courier_id": 17, "action": "dropoff", "order_id": 16319, "point_id": 66319}, {"courier_id": 20, "action": "pickup", "order_id": 11524, "point_id": 41524}, {"courier_id": 20, "action": "dropoff", "order_id": 11524, "point_id": 61524}, {"courier_id": 20, "action": "pickup", "order_id": 12255, "point_id": 42255}, {"courier_id": 20, "action": "pickup", "order_id": 12771, "point_id": 42771}, {"courier_id": 20, "action": "pickup", "order_id": 13095, "point_id": 43095}, {"courier_id": 20, "action": "pickup", "order_id": 14530, "point_id": 44530}, {"courier_id": 20, "action": "dropoff", "order_id": 12771, "point_id": 62771}, {"courier_id": 20, "action": "dropoff", "order_id": 13095, "point_id": 63095}, {"courier_id": 20, "action": "dropoff", "order_id": 12255, "point_id": 62255}, {"courier_id": 20, "action": "dropoff", "order_id": 14530, "point_id": 64530}, {"courier_id": 25, "action": "pickup", "order_id": 16967, "point_id": 46967}, {"courier_id": 25, "action": "pickup", "order_id": 12245, "point_id": 42245}, {"courier_id": 25, "action": "pickup", "order_id": 10374, "point_id": 40374}, {"courier_id": 25, "action": "pickup", "order_id": 15230, "point_id": 45230}, {"courier_id": 25, "action": "pickup", "order_id": 12493, "point_id": 42493}, {"courier_id": 25, "action": "pickup", "order_id": 13179, "point_id": 43179}, {"courier_id": 25, "action": "dropoff", "order_id": 13179, "point_id": 63179}, {"courier_id": 25, "action": "dropoff", "order_id": 12245, "point_id": 62245}, {"courier_id": 25, "action": "dropoff", "order_id": 15230, "point_id": 65230}, {"courier_id": 25, "action": "dropoff", "order_id": 10374, "point_id": 60374}, {"courier_id": 25, "action": "dropoff", "order_id": 12493, "point_id": 62493}, {"courier_id": 25, "action": "dropoff", "order_id": 16967, "point_id": 66967}, {"courier_id": 27, "action": "pickup", "order_id": 13503, "point_id": 43503}, {"courier_id": 27, "action": "dropoff", "order_id": 13503, "point_id": 63503}, {"courier_id": 30, "action": "pickup", "order_id": 14259, "point_id": 44259}, {"courier_id": 30, "action": "pickup", "order_id": 15684, "point_id": 45684}, {"courier_id": 30, "action": "pickup", "order_id": 16043, "point_id": 46043}, {"courier_id": 30, "action": "dropoff", "order_id": 14259, "point_id": 64259}, {"courier_id": 30, "action": "dropoff", "order_id": 15684, "point_id": 65684}, {"courier_id": 30, "action": "dropoff", "order_id": 16043, "point_id": 66043}, {"courier_id": 31, "action": "pickup", "order_id": 10460, "point_id": 40460}, {"courier_id": 31, "action": "pickup", "order_id": 10439, "point_id": 40439}, {"courier_id": 31, "action": "pickup", "order_id": 15294, "point_id": 45294}, {"courier_id": 31, "action": "pickup", "order_id": 12196, "point_id": 42196}, {"courier_id": 31, "action": "pickup", "order_id": 16860, "point_id": 46860}, {"courier_id": 31, "action": "dropoff", "order_id": 12196, "point_id": 62196}, {"courier_id": 31, "action": "dropoff", "order_id": 15294, "point_id": 65294}, {"courier_id": 31, "action": "dropoff", "order_id": 10460, "point_id": 60460}, {"courier_id": 31, "action": "dropoff", "order_id": 10439, "point_id": 60439}, {"courier_id": 31, "action": "dropoff", "order_id": 16860, "point_id": 66860}, {"courier_id": 34, "action": "pickup", "order_id": 15224, "point_id": 45224}, {"courier_id": 34, "action": "pickup", "order_id": 11995, "point_id": 41995}, {"courier_id": 34, "action": "dropoff", "order_id": 11995, "point_id": 61995}, {"courier_id": 34, "action": "dropoff", "order_id": 15224, "point_id": 65224}, {"courier_id": 37, "action": "pickup", "order_id": 10625, "point_id": 40625}, {"courier_id": 37, "action": "dropoff", "order_id": 10625, "point_id": 60625}, {"courier_id": 41, "action": "pickup", "order_id": 12510, "point_id": 42510}, {"courier_id": 41, "action": "pickup", "order_id": 13322, "point_id": 43322}, {"courier_id": 41, "action": "dropoff", "order_id": 12510, "point_id": 62510}, {"courier_id": 41, "action": "dropoff", "order_id": 13322, "point_id": 63322}, {"courier_id": 43, "action": "pickup", "order_id": 17163, "point_id": 47163}, {"courier_id": 43, "action": "pickup", "order_id": 11978, "point_id": 41978}, {"courier_id": 43, "action": "pickup", "order_id": 12954, "point_id": 42954}, {"courier_id": 43, "action": "pickup", "order_id": 17070, "point_id": 47070}, {"courier_id": 43, "action": "dropoff", "order_id": 11978, "point_id": 61978}, {"courier_id": 43, "action": "dropoff", "order_id": 12954, "point_id": 62954}, {"courier_id": 43, "action": "dropoff", "order_id": 17070, "point_id": 67070}, {"courier_id": 43, "action": "dropoff", "order_id": 17163, "point_id": 67163}, {"courier_id": 47, "action": "pickup", "order_id": 15921, "point_id": 45921}, {"courier_id": 47, "action": "pickup", "order_id": 14885, "point_id": 44885}, {"courier_id": 47, "action": "pickup", "order_id": 12202, "point_id": 42202}, {"courier_id": 47, "action": "pickup", "order_id": 12485, "point_id": 42485}, {"courier_id": 47, "action": "dropoff", "order_id": 12202, "point_id": 62202}, {"courier_id": 47, "action": "dropoff", "order_id": 12485, "point_id": 62485}, {"courier_id": 47, "action": "dropoff", "order_id": 14885, "point_id": 64885}, {"courier_id": 47, "action": "dropoff", "order_id": 15921, "point_id": 65921}, {"courier_id": 51, "action": "pickup", "order_id": 14064, "point_id": 44064}, {"courier_id": 51, "action": "pickup", "order_id": 15573, "point_id": 45573}, {"courier_id": 51, "action": "dropoff", "order_id": 15573, "point_id": 65573}, {"courier_id": 51, "action": "dropoff", "order_id": 14064, "point_id": 64064}, {"courier_id": 54, "action": "pickup", "order_id": 10201, "point_id": 40201}, {"courier_id": 54, "action": "pickup", "order_id": 16099, "point_id": 46099}, {"courier_id": 54, "action": "pickup", "order_id": 12025, "point_id": 42025}, {"courier_id": 54, "action": "dropoff", "order_id": 10201, "point_id": 60201}, {"courier_id": 54, "action": "dropoff", "order_id": 12025, "point_id": 62025}, {"courier_id": 54, "action": "dropoff", "order_id": 16099, "point_id": 66099}, {"courier_id": 60, "action": "pickup", "order_id": 15733, "point_id": 45733}, {"courier_id": 60, "action": "pickup", "order_id": 10371, "point_id": 40371}, {"courier_id": 60, "action": "pickup", "order_id": 12923, "point_id": 42923}, {"courier_id": 60, "action": "dropoff", "order_id": 10371, "point_id": 60371}, {"courier_id": 60, "action": "dropoff", "order_id": 12923, "point_id": 62923}, {"courier_id": 60, "action": "dropoff", "order_id": 15733, "point_id": 65733}, {"courier_id": 61, "action": "pickup", "order_id": 12520, "point_id": 42520}, {"courier_id": 61, "action": "pickup", "order_id": 12332, "point_id": 42332}, {"courier_id": 61, "action": "dropoff", "order_id": 12520, "point_id": 62520}, {"courier_id": 61, "action": "dropoff", "order_id": 12332, "point_id": 62332}, {"courier_id": 66, "action": "pickup", "order_id": 10612, "point_id": 40612}, {"courier_id": 66, "action": "pickup", "order_id": 10067, "point_id": 40067}, {"courier_id": 66, "action": "pickup", "order_id": 10059, "point_id": 40059}, {"courier_id": 66, "action": "dropoff", "order_id": 10059, "point_id": 60059}, {"courier_id": 66, "action": "dropoff", "order_id": 10067, "point_id": 60067}, {"courier_id": 66, "action": "dropoff", "order_id": 10612, "point_id": 60612}, {"courier_id": 68, "action": "pickup", "order_id": 16532, "point_id": 46532}, {"courier_id": 68, "action": "pickup", "order_id": 16449, "point_id": 46449}, {"courier_id": 68, "action": "pickup", "order_id": 12964, "point_id": 42964}, {"courier_id": 68, "action": "dropoff", "order_id": 12964, "point_id": 62964}, {"courier_id": 68, "action": "dropoff", "order_id": 16449, "point_id": 66449}, {"courier_id": 68, "action": "dropoff", "order_id": 16532, "point_id": 66532}, {"courier_id": 74, "action": "pickup", "order_id": 14572, "point_id": 44572}, {"courier_id": 74, "action": "pickup", "order_id": 13842, "point_id": 43842}, {"courier_id": 74, "action": "pickup", "order_id": 13003, "point_id": 43003}, {"courier_id": 74, "action": "pickup", "order_id": 16239, "point_id": 46239}, {"courier_id": 74, "action": "pickup", "order_id": 16102, "point_id": 46102}, {"courier_id": 74, "action": "dropoff", "order_id": 13003, "point_id": 63003}, {"courier_id": 74, "action": "dropoff", "order_id": 16102, "point_id": 66102}, {"courier_id": 74, "action": "dropoff",
